sudo: false
language: rust
cache: cargo
env:
  global:
  - RUST_BACKTRACE=1
branches:
  only:
  - master
  - "/^release-[0-9]\\.[0-9]"
  - "/^v[0-9]\\.[0-9]\\.[0-9].*/"
jobs:
  include:
  - stage: test
    name: Test Linux
    script: cargo test && ./scripts/test-examples.sh
    rust: stable
    os: linux
  - stage: test
    name: Test Mac
    script: cargo test
    rust: stable
    os: osx
  - stage: test
    name: Test Windows
    script: cargo test
    rust: stable
    os: windows
  - stage: test
    name: Benchmarks
    script: cargo bench -- --test
    rust: stable
    os: linux
  - stage: deploy
    name: Publish Linux Release
    script: ./scripts/travis-release.sh
    deploy:
      provider: releases
      api_key:
        secure: EscVlOZdcsPBlxdT2t/Z1LSCoXBPaivgGCqwcbWgk5jldmN4vfNQLMHJNG1qIb+wOtPRjbVTTbolegig3xKOXFjeClCivmnxHFRtLLIF/fhRleb3AMaP6Y8GgE2qJXRXex5tHU56l5hdvNJozAP6OdRa7nd02JaPaGcu9+YT3pwsfCWa3DtT23A7c0fRrD6nVPf9AlWWU1QL0aoS1ajzPAkT15gcdzC8NFaTxBpjHdtxl6ZrBWMbLelmIiJrPdVZyE/iAMTv2B/CZZJLVWl96M2Ri5l3HBUqJ/A91InLnv2ES7+euXezZ6M5fBllvkbQQRAUUTglXIwKs00c9CCOujGCOIdUMGy3v/9W9J/g9uaemnTWSSLxEnl15XTb6kslJgMpPGlv1o9XwsncezpS5YN0u/y0Hcb3xvp0U32DkzWJJpEPUkHgaOvY6zDZ18sck7pZci3BLFwHaSgOM1P57I7QSjgOMM/8OAvDtkMkk/l7bm8/CvqnUYWeFNf4REzZIr2mRX7E1RH1zWyIdAP906VQwEACuxvDV0EAxY6Ar3niJ4MgBvdyUc28MHtMRUXujQ9ZH0ZweKAzsV4Jrplb+N1+Z7WhBPs2QfYBoP8AV0t2zw7+g38gtd8nG9Fc8EXVQDM9vO8Oftf920OcRQ5kG0PjHYlmoqVN16r+kNz4gSE=
      file: target/artifacts/dgen-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip
      draft: true
      skip_cleanup: true
      on:
        repo: psFried/dgen
        tags: true
    os: linux
  - stage: deploy
    name: Publish Mac Release
    os: osx
    script: ./scripts/travis-release.sh
    deploy:
      provider: releases
      api_key:
        secure: EscVlOZdcsPBlxdT2t/Z1LSCoXBPaivgGCqwcbWgk5jldmN4vfNQLMHJNG1qIb+wOtPRjbVTTbolegig3xKOXFjeClCivmnxHFRtLLIF/fhRleb3AMaP6Y8GgE2qJXRXex5tHU56l5hdvNJozAP6OdRa7nd02JaPaGcu9+YT3pwsfCWa3DtT23A7c0fRrD6nVPf9AlWWU1QL0aoS1ajzPAkT15gcdzC8NFaTxBpjHdtxl6ZrBWMbLelmIiJrPdVZyE/iAMTv2B/CZZJLVWl96M2Ri5l3HBUqJ/A91InLnv2ES7+euXezZ6M5fBllvkbQQRAUUTglXIwKs00c9CCOujGCOIdUMGy3v/9W9J/g9uaemnTWSSLxEnl15XTb6kslJgMpPGlv1o9XwsncezpS5YN0u/y0Hcb3xvp0U32DkzWJJpEPUkHgaOvY6zDZ18sck7pZci3BLFwHaSgOM1P57I7QSjgOMM/8OAvDtkMkk/l7bm8/CvqnUYWeFNf4REzZIr2mRX7E1RH1zWyIdAP906VQwEACuxvDV0EAxY6Ar3niJ4MgBvdyUc28MHtMRUXujQ9ZH0ZweKAzsV4Jrplb+N1+Z7WhBPs2QfYBoP8AV0t2zw7+g38gtd8nG9Fc8EXVQDM9vO8Oftf920OcRQ5kG0PjHYlmoqVN16r+kNz4gSE=
      file: target/artifacts/dgen-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip
      draft: true
      skip_cleanup: true
      on:
        repo: psFried/dgen
        tags: true
  - stage: deploy
    name: Publish Windows Release
    os: windows
    script: "./scripts/travis-release.sh"
    deploy:
      provider: releases
      api_key:
        secure: EscVlOZdcsPBlxdT2t/Z1LSCoXBPaivgGCqwcbWgk5jldmN4vfNQLMHJNG1qIb+wOtPRjbVTTbolegig3xKOXFjeClCivmnxHFRtLLIF/fhRleb3AMaP6Y8GgE2qJXRXex5tHU56l5hdvNJozAP6OdRa7nd02JaPaGcu9+YT3pwsfCWa3DtT23A7c0fRrD6nVPf9AlWWU1QL0aoS1ajzPAkT15gcdzC8NFaTxBpjHdtxl6ZrBWMbLelmIiJrPdVZyE/iAMTv2B/CZZJLVWl96M2Ri5l3HBUqJ/A91InLnv2ES7+euXezZ6M5fBllvkbQQRAUUTglXIwKs00c9CCOujGCOIdUMGy3v/9W9J/g9uaemnTWSSLxEnl15XTb6kslJgMpPGlv1o9XwsncezpS5YN0u/y0Hcb3xvp0U32DkzWJJpEPUkHgaOvY6zDZ18sck7pZci3BLFwHaSgOM1P57I7QSjgOMM/8OAvDtkMkk/l7bm8/CvqnUYWeFNf4REzZIr2mRX7E1RH1zWyIdAP906VQwEACuxvDV0EAxY6Ar3niJ4MgBvdyUc28MHtMRUXujQ9ZH0ZweKAzsV4Jrplb+N1+Z7WhBPs2QfYBoP8AV0t2zw7+g38gtd8nG9Fc8EXVQDM9vO8Oftf920OcRQ5kG0PjHYlmoqVN16r+kNz4gSE=
      file: target/artifacts/dgen-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip
      draft: true
      skip_cleanup: true
      on:
        repo: psFried/dgen
        tags: true
stages:
  - test
  - name: deploy
    if: tag IS present
