[package]
name = "data-gen"
version = "0.1.0"
authors = ["Phil Fried <pfried@paxata.com>"]
build = "build.rs"


[dependencies]
structopt = "0.2.10"
rand = "0.5.3"
log = "0.4"
env_logger = "0.5"
lalrpop-util = "0.15.2"
regex = "1.0.1"

[build-dependencies]
lalrpop = "0.15.2"

